version: '3.4'

services:
  mongodb:
    ports:
      - 9004:27017
    volumes:
      - /mnt/data/mongodb:/data/db

  plutus-web:
    environment:
      NODE_ENV: development
    ports:
      - 9300:80
      - 9301:9229
    volumes:
        - './scripts/docker/plutus-web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'

  dummycont:
    environment:
      NODE_ENV: development
    ports:
      - 9500:80
      - 9501:9229
    volumes:
        - './scripts/docker/plutus-web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'

  plutus-api:
    environment:
      NODE_ENV: development
    ports:
      - 9400:4000
      - 9401:9229

  verdaccio:
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - '/mnt/data/verdaccio:/verdaccio/storage'
      - './scripts/docker/verdaccio/config:/verdaccio/conf'
      - './scripts/docker/verdaccio/plugins:/verdaccio/plugins'
  haproxy:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./scripts/docker/haproxy/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./scripts/docker/haproxy/config/routes.map:/usr/local/etc/haproxy/maps/routes.map:ro
      - ./scripts/docker/haproxy/pem/polysets.pem:/etc/haproxy/pem/polysets.pem
      - ./scripts/docker/haproxy/config/whitelist.acl:/usr/local/etc/haproxy/acl/whitelist.acl:ro
